### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by alexcrow** [gonicus/gofaxip#16]
Hi gonicus,

Is this project still being maintained? Just don't see a lot of activity - of course that could be because it just works ;-)

Thanks,

Alex

**Comment by markuslindenberg** [comment]
Hi Alex.

Yes, absolutely! It doesn't have much activity right now because it just works for the use cases we had in mind.

Sure there's some minor things I'd like to address when I have the time: 

* Support for AvantFAX
* Display of transfer rate in notifications for received faxes
* Repository Refactoring so installing using `go get ...` is possible
* Binary release w/ distribution packages
* ...

But I'll address those as time permits or when requirements come up.
