### ISSUE TITLE
ATA

### ISSUE THREAD

**Issue by nde1** [gonicus/gofaxip#17]
Hi I know that gofaxip hooks into the event socket and controls the dialplan.  Is it possible to fax to a gateway from an ATA using FS?

**Comment by nde1** [comment]
I think I got this resolved by editing the FaxDispatch & faxrcvd file.

**Comment by markuslindenberg** [comment]
Oh great. Yeah, should be possible of course. From the SIP point of view gofaxip's FreeSWITCH is just a User Agent, you can send faxes to gofaxip's SIP interface it without registration. 

It's currently not possible to register to ATA to freeswitch or have a dialplan/pbx funtionality in gofaxip because that would make the FreeSWITCH interaction much more complicated. Right now the FreeSWITCH config is extremely simple and I'd want to keep it that way. If a PBX or SIP registrar is needed it should be on a seperate system.
