### ISSUE TITLE
gofaxsend config is inflexible

### ISSUE THREAD

**Issue by abma** [gonicus/gofaxip#20]
dialstring (in transmission.go) should be completely read from the config file.

because "api originate sofia/gateway/..." is hardcoded a lot of stuff isn't possible: i.e. the dialplan is completely bypassed because of this.

**Comment by markuslindenberg** [comment]
Hi abma, 

sorry for the late reply. 

The issue is a bit more complicated and it's a deliberate choice to hardcode the dial string generation and run FreeSWITCH without a dialplan. It is currently not possible to integrate gofaxip into an existing PBX dialplan because some features that are frequently used in the dialplan (like disappearing local channels)  would not work with gofaxip as is. 
Gofaxip tracks all incoming and originated channels and reports progress back to Hylafax. This tracking can get problematic when channel UUIDs are mapped and changed and/or other fun stuff happens in the dialplan. I'm not saying it's impossible, but it would require some changes and make gofaxip more complicated.

That's why we chose to hardcode those options for now and provide all configuration files necessary to use a stripped down FreeSWITCH exclusively as SIP User Agent for a HylaFax fax server. We only need 9 out of 146 FreeSWITCH modules and the most simple FreeSWITCH configuration. Most gofaxip users have no or only very basic FreeSWITCH knowledge so it's crucial to make that part as easy to install and operate as possible and provide configuration that works out of the box.
I also consider seperating fax and telephony servers a good design choice. They can be connected using SIP and even be installed on the same machine on different ports or namespaces.

So it's currently unlikely that I will put resources into making this possible as I don't see the added value (and our customers don't have use for it) and want to avoid introducing complexity for this.
Of course if it turns out to be possible to add robust support for using gofaxip in existing dialplans without much effort i'm open to accepting pull requests.
