### ISSUE TITLE
docker build

### ISSUE THREAD

**Issue by gedw99** [gonicus/gofaxip#33]
any chance we can have a docker built to make it easier for people to get involved ?

I can help bring one up, but do you want this as a PR ?

**Comment by denzs** [comment]
Are you talking about a container for building the packages or for running gofaxip?

To be honest at the moment i dont really see the benefit in using docker with gofaxip...

Building gofaxip should be quite simple using the usual go build process.

And for running (while considering best practices) you would run a container for every application, which would make three containers for gofaxip, freeswitch and hylafax where you would have to share filesystems and forward a serious amount of ports for media. This would be somewhat complicated for a "normal" deployment and if you want to run gofaxip on kubernetes for example you propably need a lot of custom logic anyway...

But feel free to give some more details on your use case :)

**Comment by gedw99** [comment]
Yeah it's about being able to put into CI and CD.
It's alot easier these days using Google container builder.

Do you want me to try ? Will you accept a PR ?

**Comment by denzs** [comment]
Sounds good, feel free to submit a PR :+1:

**Comment by gedw99** [comment]
Why do they need to share file systems ?
Can't we instead share messages via NATS and let each maintain its own filesystem ?

**Comment by denzs** [comment]
HylaFAX is using traditional file locking mechanisms to make sure the modems and qfile are not accessed concurrently. gofaxsend and gofaxd implements these mechanisms too...

If you split gofax and HylaFAX into different machines this will get difficut.
I am not saying it is not possible, but you would have to add extra components for the communication and at the moment i dont see the big amount of benefit compared to the amount of complexity which would be added. And you would need another container to run gnatsd...

Beside of the complexity i dont think it meets the current best practices to exchange files via nats?!

**Comment by gedw99** [comment]
ok yep YAGNI. Maybe laters for scaling ....

SO if i get this, we want 3 dockers with a shared FS between them ?

**Comment by markuslindenberg** [comment]
There are two possible use cases for Dockerfiles:

* Automated building / packaging / CI testing
* Deployment on a container orchestration system

For CI I see a lot of value in a Dockerfile, but for deployment the scenario is a lot more complex but possibly doable: FreeSWITCH, Hylafax and gofaxip need to run in the same pod w/ the same uid and a shared `/var/spool/hylafax` filesystem. I'm a strong proponent of one process per container, so using a init system to run the whole solution inside a single Dockerfile isn't really something we would want to promote. 

IMHO that makes orchestration w/ Swarm or Kubernetes mandatory to run a containerized fax server. Plus there is some added complexity because the FreeSWITCH SIP endpoint is placed behind Docker's NAT, something you have to consider when deploying.

I don't think this would make it easier for people to get started, but it certainly is an interesting scenario for scalable / survivable deployments on the higher end. 

I think it would be wise to have all necessary Dockerfiles in a contrib folder first and we'd be happy to accept contributions but I'm reluctant to enable automated image builds as I worry that that will cause the expectation that setting up gofaxip inside containers is an easy task and a good way to get started which I think is not the case.

**Comment by gedw99** [comment]
Ok that's a huge help.

Lxd might be a good option then, because all containers there get a real IP on the network from the DHCP router when I run it at home.
So no NAT needed.
Lxd running inside Ubuntu core is a. Nice option for on premise situations on a small arm or intel board 
So that's one option.

In the cloud you can run lxd within the Google infrastructure but I am not sure how it will handle NAT.

I agree about one container per process. Kiss principle.
But for v1 of thing it might make sense to through it all in one container to get going and stabilise it and then for v2 seperate it out and deal with the shared file system aspects then.


Let me know your thoughts..

**Comment by vasyugan** [comment]
If docker is not workable, what about a custom raspbian image? Hylafax, Freeswitch and gofaxip would run just fine on a raspberrypi, just setting it up is a real pain in the ass, mostly because freeswitch is such a beast.

**Comment by denzs** [comment]
As we dont have a use case for a dedicated raspbian based gofax.ip image at the moment,
it is unlikely that we will put effort in it right now...

But it should be doable pretty easy!

Although there are no binary packages for armhf, there is already documentation for building freeswitch on raspbian
see https://freeswitch.org/freeswitch-1-7-installed-on-raspberry-pi-2/ for an example...

If you want to provide a script to build an image we would be happy to add it to a contrib folder!

**Comment by gedw99** [comment]
I use gokrazy for RPI.
Its golang based and really the way to do it IMHO
